### ISSUE TITLE
LIME explanation throws error

### ISSUE THREAD

**Issue by stefanDeveloper** [stefanDeveloper/explainable-prediction_covid19#9]
Wenn ich versuche LIME `lime_explain` bekomme ich folgenden Fehler:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/covid-cxr/src/interpretability/lime_explain.py", line 108, in <module>
    lime_dict = setup_lime()
  File "/content/covid-cxr/src/interpretability/lime_explain.py", line 55, in setup_lime
    lime_dict['MODEL'] = load_model(cfg['PATHS']['MODEL_TO_LOAD'], compile=False)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 166, in load_model_from_hdf5
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by stefanDeveloper** [comment]
Gleiches Problem tritt auch bei `gradcam.py` auf

**Comment by stefanDeveloper** [comment]
Consider #1 when fixing LIME

**Comment by DavidHector** [comment]
Das ist ein Pfad-Problem, weil in der config nur model.h5 steht, aber der richtige Name model202108191505.h5 oder sowas ist.

**Comment by stefanDeveloper** [comment]
Hä, laut Tensorflow musste ich das Package installieren h5py<=3.0.0 installieren. Den Pfad in der Config hatte ich da auch schon angepasst

**Comment by DavidHector** [comment]
Hmm richtig komisch
